In [3]:
import pandas as pd
prediction = pd.read_parquet(r'C:\Users\蒋大王\Desktop\量化\截面多因子模型\03模型训练层\experiments\exp_20260303_155448\predictions.parquet')
prediction

                       pred_score  actual_return  fold_id
date       stock_code
2013-07-02 000001.SZ    -0.007484       0.008333        0
           000002.SZ    -0.004833      -0.047325        0
           000004.SZ    -0.011320      -0.008867        0
           000006.SZ    -0.010588      -0.047733        0
           000007.SZ    -0.008692       0.016277        0
...                           ...            ...      ...
2026-01-22 688807.SH     0.009626       0.163755       50
           688809.SH     0.009626       0.073882       50
           688819.SH     0.011184      -0.036963       50
           688981.SH     0.010977      -0.093060       50
           689009.SH     0.010977      -0.081227       50

[11246047 rows x 3 columns]

In [1]:
import pandas as pd
sum = pd.read_parquet(r'C:\Users\蒋大王\Desktop\量化\截面多因子模型\03模型训练层\experiments\test_001_ranking_v1\predictions.parquet')
sum

              date stock_code  pred_score  actual_return  fold_id
0       2023-10-24  000001.SZ   -0.017553      -0.023787        0
1       2023-10-24  000002.SZ   -0.035773       0.000845        0
2       2023-10-24  000004.SZ    0.044128       0.086853        0
3       2023-10-24  000006.SZ   -0.022428       0.266821        0
4       2023-10-24  000007.SZ   -0.017258       0.008097        0
...            ...        ...         ...            ...      ...
2776182 2026-01-21  688807.SH   -0.008078       0.081340        8
2776183 2026-01-21  688809.SH   -0.003934      -0.010384        8
2776184 2026-01-21  688819.SH   -0.011161      -0.030174        8
2776185 2026-01-21  688981.SH    0.014848      -0.108156        8
2776186 2026-01-21  689009.SH   -0.006987      -0.048240        8

[2776187 rows x 5 columns]

In [1]:
import pandas as pd
df = pd.read_parquet(r"C:\Users\蒋大王\Desktop\量化\截面多因子模型\03模型训练层\experiments\test_002\predictions.parquet")
df.head()

        date stock_code  pred_score  actual_return  fold_id
0 2023-06-30  000001.SZ    0.013160       0.091719        0
1 2023-06-30  000002.SZ    0.016093       0.086305        0
2 2023-06-30  000004.SZ    0.009755       0.211148        0
3 2023-06-30  000006.SZ    0.013171       0.141876        0
4 2023-06-30  000007.SZ    0.009956       0.098434        0

In [2]:
import pandas as pd
df = pd.read_parquet(r"C:\Users\蒋大王\Desktop\量化\截面多因子模型\03模型训练层\experiments\test_001_fined_20_v1\smoothed_predictions.parquet")
df.head()

,date,stock_code,pred_score,pred_score_smooth,actual_return,fold_id
0,2025-06-26,000001.SZ,0.004123,0.004123,-0.003234,0
5115,2025-06-27,000001.SZ,0.002859,0.003474,0.017298,0
10230,2025-06-30,000001.SZ,0.002995,0.003306,0.033167,0
15345,2025-07-01,000001.SZ,0.003064,0.003241,0.003249,0
20461,2025-07-02,000001.SZ,0.003064,0.003202,0.014599,0